### ISSUE TITLE
Teamcity Download Needs Update

### ISSUE THREAD

**Issue by jaysonhelseth** [JetBrains/teamcity-dotnet-plugin#29]
I have downloaded the plugin from the Teamcity plugin site and it is not allowing me to build with dotnet by pointing at a .csproj file. I see in your comments that you have that you have added that feature. Can you update the link on the Teamcity site, or provide instructions on how to compile your source into a plugin?

Thanks,

Jayson

**Comment by dtretyakov** [comment]
@jaysonhelseth, could you please share teamcity .net core plugin version and `dotnet` cli tools version installed on this build agent? Also it would be great to look at the build step output to investigate it.

**Comment by jaysonhelseth** [comment]
.net core plugin: 0.3.2
dotnet cli: 1.0.0-preview2-1-003177

Here is the dotnet error:
**Step 1/2: Build (.NET Core (dotnet))
[15:40:33][Step 1/2] Failed to start build runner 'dotnet'
[15:40:33]
[Step 1/2] jetbrains.buildServer.agent.ToolCannotBeFoundException: Invalid tool dotnet distribution at C:\Program Files\dotnet\
	at jetbrains.buildServer.dotnet.DotnetToolProvider.getPath(DotnetToolProvider.java:45)
	at jetbrains.buildServer.dotnet.DotnetToolProvider.getPath(DotnetToolProvider.java:68)
	at jetbrains.buildServer.agent.impl.BuildRunnerContextImpl.getToolPath(BuildRunnerContextImpl.java:175)
	at jetbrains.buildServer.agent.runner.BuildServiceAdapter.getToolPath(BuildServiceAdapter.java:84)
	at jetbrains.buildServer.dotnet.DotnetRunnerBuildService.makeProgramCommandLine(DotnetRunnerBuildService.java:53)
	at jetbrains.buildServer.agent.runner2.SingleCommandLineBuildSessionAdapter.makeProgramCommandLine(SingleCommandLineBuildSessionAdapter.java:54)
	at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.executeProcess(GenericCommandLineBuildProcess.java:79)
	at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.waitFor(GenericCommandLineBuildProcess.java:269)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:75)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:295)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:53)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:259)
	at java.lang.Thread.run(Thread.java:745)
[15:40:33][Step 1/2] Step Build (.NET Core (dotnet)) failed with unexpected error**

**Comment by dtretyakov** [comment]
@jaysonhelseth, ok, you need to instal .net core plugin [v0.6.1](https://plugins.jetbrains.com/teamcity/plugin/9190) and  .net core cli tools version [1.0.0-preview3](https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md).

**Comment by dtretyakov** [comment]
Also, please make sure that .net core cli has been successfully detected on the build agent and if not define dotnet tool path in the PATH env var: https://blog.jetbrains.com/teamcity/2016/11/teamcity-dotnet-core/

**Comment by jaysonhelseth** [comment]
I have version 0.6.1 now. I hesitate to move to preview3. I did get a different error in my build log now.

**Step 1/3: .NET Core (dotnet)
[16:41:31][Step 1/3] Starting: "C:\Program Files\dotnet\dotnet.exe" restore webdotnetcore.sln
[16:41:31][Step 1/3] in directory: C:\TeamCity\buildAgent\work\98592d4b866641b0
[16:41:31][Step 1/3] error: Invalid input 'webdotnetcore.sln'. The file type was not recognized.
[16:41:31][Step 1/3] Process exited with code 1
[16:41:31][Step 1/3] Step .NET Core (dotnet) failed
[16:41:31]Step 2/3: .NET Core (dotnet)
[16:41:31][Step 2/3] Build step .NET Core (dotnet) is skipped because the previous step has failed**

**Comment by dtretyakov** [comment]
@jaysonhelseth, dotnet cli 1.0.0-preview2-1-003177 only works with project.json based projects, so you have to use preview3 to be able to build *.sln and *.csproj files:
https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/

**Comment by jaysonhelseth** [comment]
I installed the preview and restarted the Teamcity Server. I feel like I am getting closer. Here is my new error:
****Step 1/3: .NET Core (dotnet)
[08:53:39][Step 1/3] Starting: "C:\Program Files\dotnet\dotnet.exe" restore webdotnetcore.sln
[08:53:39][Step 1/3] in directory: C:\TeamCity\buildAgent\work\98592d4b866641b0
[08:53:40][Step 1/3] Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
[08:53:40][Step 1/3] C:\TeamCity\buildAgent\work\98592d4b866641b0\src\webdotnetcore\webdotnetcore.csproj : error MSB4057: The target "_GenerateRestoreGraphProjectEntry" does not exist in the project.
[08:53:40][Step 1/3] Process exited with code 1
[08:53:40][Step 1/3] Step .NET Core (dotnet) failed**

**Comment by latop2604** [comment]
Does each command run correctly on your dev environment?

**Comment by jaysonhelseth** [comment]
The restore worked just fine in my dev environment. My dev environment is Windows 10 64 bit enterprise edition, running dotnet version 1.0.0-preview4-004233. I didn't realize that my dev environment was a newer version than my continuous integration environment.

**Comment by latop2604** [comment]
You can try to edit global.json file and downgrade the targeted dotnet sdk to match your tc environment

**Comment by jaysonhelseth** [comment]
It seems like I am having problems retrieving packages when building with Teamcity.

**[Step 1/3] C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\NuGet.targets(70,5): error MSB4018: The "RestoreTask" task failed unexpectedly. [C:\TeamCity\buildAgent\work\98592d4b866641b0\webdotnetcore.sln]
[11:09:46][Step 1/3] C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\NuGet.targets(70,5): error MSB4018: System.AggregateException: One or more errors occurred. (Failed to retrieve information from remote source 'C:\Packages'.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve information from remote source 'C:\Packages'. [C:\TeamCity\buildAgent\work\98592d4b866641b0\webdotnetcore.sln]**

This does work from command line on the Teamcity box.

**Comment by dtretyakov** [comment]
@jaysonhelseth, could you please try to update to the latest plugin version with a fixes in .net cli preview4 support: https://plugins.jetbrains.com/teamcity/plugin/9190

**Comment by jaysonhelseth** [comment]
This finally worked! Thank you for your help.
