### ISSUE TITLE
NullPointerException in TestArgumentsProvider

### ISSUE THREAD

**Issue by the-eejay** [JetBrains/teamcity-dotnet-plugin#32]
Greetings,

I believe there's a bug in the TestArgumentsProvider.

![image](https://cloud.githubusercontent.com/assets/2044982/22961154/952bf61e-f38f-11e6-9efb-4a20b01eaf47.png)

When I don't supply a value for the temp directory in the dotnet test command (pictured above), I get a Null Pointer Exception. Here's the (abbreviated) stacktrace:

`Step 20/25: Run Unit Tests (.NET Core (dotnet))
[13:35:36][Step 20/25] Failed to start build runner 'dotnet'
[13:35:36]
[Step 20/25] kotlin.KotlinNullPointerException
	at jetbrains.buildServer.dotnet.dotnet.TestArgumentsProvider.getArguments(TestArgumentsProvider.kt:57)
	at jetbrains.buildServer.dotnet.DotnetRunnerBuildService.makeProgramCommandLine(DotnetRunnerBuildService.kt:43)
	at jetbrains.buildServer.agent.runner2.SingleCommandLineBuildSessionAdapter.makeProgramCommandLine(SingleCommandLineBuildSessionAdapter.java:54)
	at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.executeProcess(GenericCommandLineBuildProcess.java:78)
	at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.waitFor(GenericCommandLineBuildProcess.java:260)
	... <snip> ...
	at java.lang.Thread.run(Thread.java:745)`

I think Line 55 of TestArgumentsProvider.kt should be changed from:

`if (!outputValue.isNullOrBlank()) {`

To:

`if (!tempValue.isNullOrBlank()) {`

Regards,
Ethan

**Comment by dtretyakov** [comment]
@the-eejay, thanks for reporting. You can update this plugin to the latest version: https://plugins.jetbrains.com/teamcity/plugin/9190
